language: elixir
elixir:
  - 1.0.3
otp_release:
  - 17.0
  - 17.1
  - 17.4
sudo: false # to use faster container based build environment
script:
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
